name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context:.
          file:./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/wisecow:latest

      - name: Deploy to Kubernetes
        uses: kubernetes/deploy-action@v2
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          deployment: wisecow-deployment
          image: ${{ secrets.DOCKER_USERNAME }}/wisecow:latest
          namespace: default
